apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gio-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/callmeteus/site.git
    targetRevision: master
    path: .infra/production/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: gio-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
